# Generated by Django 4.0.4 on 2022-06-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_url_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user_like',
            new_name='users_like',
        ),
    ]
